### PR TITLE
Dynamic Keys

### PR DESCRIPTION
**Pull request by jluftcimpress**
Adding the ability to dynamically set the secret key and ID to something other than 'secret' / 'id'

signed and ready

### CODE REVIEW

**Comment by jluftcimpress** [comment]
@chrisoverzero - ending up making a new pull request to make the commits cleaner - and signed from the get-go

**Comment by chrisoverzero** [comment]
@jluftcimpress LGTM. Please confirm you're OK with the slight changes I made, and I think we'll be good to go.

**Comment by jluftcimpress** [comment]
looks good @chrisoverzero - thanks again!

**Comment by chrisoverzero** [comment]
Published as version 2.2.0.

**Pull request merged**
